### ISSUE TITLE
Trivial: iDiscounts: Admin Web: Создание бенефита: Добавление категории: Грамматическая ошибка

### ISSUE THREAD

**Issue by AnastasiyaSoroka** [wldyslw/benefits.bugtracker#1]
Создание бенефита: Добавление категории
Ошибка в тексте
![1](https://user-images.githubusercontent.com/48205053/53725656-7964e400-3e7d-11e9-9cb6-ebce5189f359.png)

**Comment by LashaLoi** [comment]
done

**Comment by AnastasiyaSoroka** [comment]
Closed
