### ISSUE TITLE
Major: iDiscounts: Admin Web: Создание бенефита: Отсутствует кнопка Cancel или её аналог

### ISSUE THREAD

**Issue by AnastasiyaSoroka** [wldyslw/benefits.bugtracker#11]
1. Open Admin Web
2. Log in
3. Выберите город
4. Создание бенефита

Отсутствует кнопка Cancel или её аналог. Пользователь передумал и хочет всё отменить.

**Comment by AnastasiyaSoroka** [comment]
То же самое при редактировании существующего бенефита

**Comment by LashaLoi** [comment]
done

**Comment by AnastasiyaSoroka** [comment]
closed
