### ISSUE TITLE
Trivial: iDiscounts: Admin Web: Создание бенефита: при выборе города появляется секция Добавление категории

### ISSUE THREAD

**Issue by AnastasiyaSoroka** [wldyslw/benefits.bugtracker#12]
1. Open Admin Web
2. Log in
3. Выберите город
4. Создание бенефита ->  Обратите внимание что на дефалтовой странице только одна секция Добавить Бенефит
![4](https://user-images.githubusercontent.com/48205053/53730581-69530180-3e89-11e9-900a-26b7c2c2a201.png)

5. Выберете город
Result: неожиданно появляется возможноть добавить категорию
![5](https://user-images.githubusercontent.com/48205053/53730654-a0291780-3e89-11e9-94e5-c531ff8e167b.png)

Expected result:
Вынести создание категории на отдельную страницу
Или
Добавление категории добавить на дефалтовую страницу

**Comment by AnastasiyaSoroka** [comment]
Expected result:
1. Вынести создание категории на отдельную страницу
Или
2. Добавление категории добавить на дефалтовую страницу

**Comment by AnastasiyaSoroka** [comment]
С новым билдом секция для добавления категории отсутствует. Появилась кнопка Добавить категорию.

Баг валиден и с ней
![18](https://user-images.githubusercontent.com/48205053/53878913-2d04da00-401e-11e9-8a6a-76105caa283f.png)

**Comment by LashaLoi** [comment]
done
