### ISSUE TITLE
Major: Discounts: комментарий и оценка отражаются только после повторного входа/открытия страницы заведения

### ISSUE THREAD

**Issue by Alena-Shurakova** [wldyslw/benefits.bugtracker#14]
**Describe the bug**
Для того, чтобы увидеть отправленный/отредактированный комментарий или удалить его, необходимо либо выйти из приложения и зайти заново, либо повторно открыть страницу  заведения, о котором был оставлен отзыв.

**To Reproduce**
Шаги отражены  на видео в аттаче
1. Открыть любое заведение, например, "The Хмель"
2. Оставить отзыв: 5 звезд, описание "!".
3. Перейти в меню выбора заведений.
4. Найти  заведение "The Хмель"
5. Обновить страницу

**Expected behavior**
Изменения в комментарии отражаются после выхода в меню выбора заведения.

**Video**
[comments.zip](https://github.com/wldyslw/benefits.bugtracker/files/2926280/comments.zip)

**Comment by wldyslw** [comment]
Fixed in the latest release

**Comment by Alena-Shurakova** [comment]
Reopened. The problem is the same.

**Comment by wldyslw** [comment]
Done, will be published in the next build

**Comment by Alena-Shurakova** [comment]
Fixed.
