### ISSUE TITLE
Critical: No confirmation message 

### ISSUE THREAD

**Issue by SKastsiukovich** [wldyslw/benefits.bugtracker#16]
**Steps to reproduce**
Log in
Open any place
Rate the place and add comment
Delete this comment

**Expected result**
Before deleting appears confirmation message like a "Are u sure...?"
**Actual result**
No confirmation message

**Comment by wldyslw** [comment]
Done, will be published in the next build

**Comment by SKastsiukovich** [comment]
No `delet` button for long message

**Comment by wldyslw** [comment]
Directly connected with #18 and fixed in the latest release

**Comment by Alena-Shurakova** [comment]
Fixed.
