### ISSUE TITLE
Critical: No opportunity to view long comments

### ISSUE THREAD

**Issue by SKastsiukovich** [wldyslw/benefits.bugtracker#19]
Log in
Open any place with comments
Rate the place and add long comment like a:
;dreswbvgnfpontest;dreswbvgnfpontest;dreswbvgnfpontest;dreswbvgnfpontest;dreswbvgnfpontest;dreswbvgnfpontest;dreswbvgnfpontest;dreswbvgnfpontest;dreswbvgnfpontest;dreswbvgnfpontest;dreswbvgnfpontest;dreswbvgnfpontest;dreswbvgnfpontest;dreswbvgnfpontest;dreswbvgnfpontest;dreswbvgnfpontest;dreswbvgnfpontest;dreswbvgnfpontest;dreswbvgnfpontest;dreswbvgnfpontest;dreswbvgnfpontest;dreswbvgnfpontest;dreswbvgnfpontest;dreswbvgnfpontest;dreswbvgnfpontest;dreswbvgnfpontest;dreswbvgnfpontest;dreswbvgnfpontest;dreswbvgnfpontest;dreswbvgnfpontest;dreswbvgnfpontest;dreswbvgnfpontest;dreswbvgnfpontest;dreswbvgnfpontest;dreswbvgnfpontest;dreswbvgnfpontest;dreswbvgnfpontest;dreswbvgnfpontest;dreswbvgnfpontest;dreswbvgnfpontest

Expected result
Long comments required put in dropdown
Actual result
No opportunity to view long comments
![2019-03-04_1613](https://user-images.githubusercontent.com/48204730/53735629-85aa6a80-3e98-11e9-83ab-bbbd0ce08c0f.png)

**Comment by wldyslw** [comment]
Fixed in latest release

**Comment by SKastsiukovich** [comment]
Required "more" button. Will be fixed in another issue
