### ISSUE TITLE
Critical: iDiscounts: Admin Web: Создание бенефита: Добавление недоступно при заполненых полях

### ISSUE THREAD

**Issue by AnastasiyaSoroka** [wldyslw/benefits.bugtracker#2]
1. Open Admin Web
2. Создание бенефита
3. Заполните все поля для бенефита

Result: Кнопка Добавить недоступна

![2](https://user-images.githubusercontent.com/48205053/53725856-dd87a800-3e7d-11e9-9095-34dc5c275377.png)

**Comment by LashaLoi** [comment]
Сперва нужно добавить локацию, после чего поля широта, долгота обнулятся и можно будет добавить еще локации. То же самое со скидкой.

**Comment by AnastasiyaSoroka** [comment]
Воспроизведено с новой версией

![image](https://user-images.githubusercontent.com/48205053/53963452-69a80280-40fe-11e9-983c-1fde0434ba68.png)

**Comment by LashaLoi** [comment]
вы не нажалт на кнопки + в полях "Скидки" и  "Адрес"

**Comment by AnastasiyaSoroka** [comment]
Какой плюс если поля заполнены? Может и  к остальным тогда прикрепить плюсик) почему бы нет

+ в данном случае выглядит как добавление дополнительного адреса и дополнительной скидки

**Comment by LashaLoi** [comment]
done

**Comment by Alena-Shurakova** [comment]
Fixed.
