### ISSUE TITLE
Trivial: iDiscounts: Admin Web: Existing Benefit: Два поля для Скидок

### ISSUE THREAD

**Issue by AnastasiyaSoroka** [wldyslw/benefits.bugtracker#20]
1. Open Admin Web
2. Log in
3. Select any category
4. Edit any benefit

Result: Два поля Скидки
![12](https://user-images.githubusercontent.com/48205053/53735915-5a744b00-3e99-11e9-924f-feaada2a78f8.png)

Expected result:
Если нет никаких дополнительных скидок - поле должно быть одно. Смысл во второй пустом?

**Comment by LashaLoi** [comment]
done
