### ISSUE TITLE
Trivial: iDiscounts: Admin Web: it's a good practice make 2 similar forms in the same way

### ISSUE THREAD

**Issue by AnastasiyaSoroka** [wldyslw/benefits.bugtracker#21]
Добавить бенефит vs Обновить бенефит
Можно ли сделать их одинаковыми? (Размер полей, расположение)

![11](https://user-images.githubusercontent.com/48205053/53736063-c060d280-3e99-11e9-9cdb-d08ba7e2aad6.png)

**Comment by LashaLoi** [comment]
done

**Comment by Alena-Shurakova** [comment]
Fixed.
