### ISSUE TITLE
Major: Rate not displays

### ISSUE THREAD

**Issue by SKastsiukovich** [wldyslw/benefits.bugtracker#22]
**Steps to reproduce**
Log in
Open any place 
Rate the place and add long comment 
Close the Place page
Find this Place in list
Observe

Expected result
Set rate should displays in list of places 
Actual result
Set rate not displays in list of places

**Comment by wldyslw** [comment]
Fixed in the latest release

**Comment by SKastsiukovich** [comment]
Still reproduce

**Comment by SKastsiukovich** [comment]
Reproduced on mobile

**Comment by SKastsiukovich** [comment]
Still reproduce on Web and Mobile

**Comment by wldyslw** [comment]
Done, will be published in the next build

**Comment by SKastsiukovich** [comment]
Still reproduce on mobile

**Comment by Alena-Shurakova** [comment]
Fixed on Android

**Comment by SKastsiukovich** [comment]
Fixed
