### ISSUE TITLE
Trivial: iDiscounts: Admin Web: Редактирование бенефита: Форма Добавить Локацию названа неверно

### ISSUE THREAD

**Issue by AnastasiyaSoroka** [wldyslw/benefits.bugtracker#23]
1. Open Admin Web
2. Log in -> Main page opened
3. Select any category
4. Edit any benefit
5. Click Добавить Локацию

Result: Добавить бенефит

![13](https://user-images.githubusercontent.com/48205053/53736385-a1af0b80-3e9a-11e9-9593-828efc857a54.png)

Expected: Добавить локацию

**Comment by LashaLoi** [comment]
done

**Comment by AnastasiyaSoroka** [comment]
closed
