### ISSUE TITLE
Critical: iDiscounts: Admin Web: Редактирование бенефита: кнопка Обновить: GraphQL error

### ISSUE THREAD

**Issue by AnastasiyaSoroka** [wldyslw/benefits.bugtracker#24]
1. Open Admin Web
2. Log in -> Main page opened
3. Select any category
4. Edit any benefit
5. Click Обновить

Result: GraphQL error: child "url" fails because ["url" is required]
![14](https://user-images.githubusercontent.com/48205053/53736744-af18c580-3e9b-11e9-807c-6719d055147e.png)

Expected result: No errors. Benefit was updated

**Comment by LashaLoi** [comment]
done
