### ISSUE TITLE
Major: iDiscounts: Admin Web: Дополнительная локация не сохраняется

### ISSUE THREAD

**Issue by AnastasiyaSoroka** [wldyslw/benefits.bugtracker#26]
1. Open Admin Web
2. Log in -> Main page opened
3. Select any category
4. Edit any benefit
5. Add additional location
![15](https://user-images.githubusercontent.com/48205053/53737483-b5a83c80-3e9d-11e9-9a31-cdd529b1bd69.png)
6. Click Обновить
7. Go to the Main list
8. Please select benefit from Step4 again

Result:
![16](https://user-images.githubusercontent.com/48205053/53737547-e4beae00-3e9d-11e9-9039-587f8aeee201.png)

**Comment by AnastasiyaSoroka** [comment]
I believe that the reason was describe in https://github.com/wldyslw/benefits.bugtracker/issues/24

**Comment by LashaLoi** [comment]
done
