### ISSUE TITLE
Search field: adding of restriction on quantity of inputting symbols

### ISSUE THREAD

**Issue by Alena-Shurakova** [wldyslw/benefits.bugtracker#28]
**Description of enhancement:**
There are no restriction on quantity of symbols which user can input in the search field. It is worth to consider variant of creation such a restriction.

**Steps to reproduce:**
1. Open web application Discounts
2 Input in the search field the following text: "fnjsdhjgjngjgjgjngnsnnfjhjhgjkhjhjhjhdmm;lpsdfghjkl.,mnbvxfnjsdhjgjngjgjgjngnsnnfjhjhgjkhjhjhjhdmm;lpsdfghjkl.,mnbvxfnjsdhjgjngjgjgjngnsnnfjhjhgjkhjhjhjhdmm;lpsdfghjkl.,mnbvxfnjsdhjgjngjgjgjngnsnnfjhjhgjkhjhjhjhdmm;lpsdfghjkl.,mnbvxfnjsdhjgjngjgjgjngnsnnfjhjhgjkhjhjhjhdmm;lpsdfghjkl.,mnbvxfnjsdhjgjngjgjgjngnsnnfjhjhgjkhjhjhjhdmm;lpsdfghjkl.,mnbvxfnjsdhjgjngjgjgjngnsnnfjhjhgjkhjhjhjhdmm;lpsdfghjkl.,mnbvxfnjsdhjgjngjgjgjngnsnnfjhjhgjkhjhjhjhdmm;lpsdfghjkl.,mnbvxfnjsdhjgjngjgjgjngnsnnfjhjhgjkhjhjhjhdmm;lpsdfghjkl.,mnbvxfnjsdhjgjngjgjgjngnsnnfjhjhgjkhjhjhjhdmm;lpsdfghjkl.,mnbvxfnjsdhjgjngjgjgjngnsnnfjhjhgjkhjhjhjhdmm;lpsdfghjkl.,mnbvxfnjsdhjgjngjgjgjngnsnnfjhjhgjkhjhjhjhdmm;lpsdfghjkl.,mnbvx"

**Actual result**: inputting of such quantity of symbols is available for user.
**Expected result**: inputting of such quantity of symbols is unavailable for user.

**Note:** Enhancement is common for web application and mobile (both with iOS and Android versions).

**Screenshots**:

Web application: 
![image](https://user-images.githubusercontent.com/48205218/53802018-c87c4900-3f51-11e9-98e5-41e39b35aa29.png)

Android mobile: 
![screenshot_2019-03-05-14-21-27](https://user-images.githubusercontent.com/48205218/53802116-08433080-3f52-11e9-8cb3-1264eb727b40.png)

iOS mobile:
![d5063ad3-31a1-4409-a8c5-885d2595a3d4](https://user-images.githubusercontent.com/48205218/53802301-8e5f7700-3f52-11e9-803e-23761e1e8c40.jpg)

**Comment by wldyslw** [comment]
Done, will be published in the next build

**Comment by Alena-Shurakova** [comment]
Fixed in web application. 
Actual for mobile.

**Comment by andrewworld** [comment]
Fixed in last release

**Comment by Alena-Shurakova** [comment]
Fixed on Android

**Comment by SKastsiukovich** [comment]
Fixed
