### ISSUE TITLE
Trivial: iDiscounts: Admin Web: Множественный выбор города при создании бенефита

### ISSUE THREAD

**Issue by AnastasiyaSoroka** [wldyslw/benefits.bugtracker#3]
1. Open Admin Web
2. Log in
3. Выберите город
4. Создание бенефита
5. Выберите город

Может имеет смысл заполнять город на шаге 5 автоматом? используя в качестве значение Шаг3

**Comment by LashaLoi** [comment]
Я сделал чтобы значение текущего города ставилось по умолчанию, чтобы потом если надо, можно было добавить бенефит в другой город.

**Comment by Alena-Shurakova** [comment]
Done
