### ISSUE TITLE
Trivial: Improvement: Map: Highlight the divide of country 

### ISSUE THREAD

**Issue by SKastsiukovich** [wldyslw/benefits.bugtracker#30]
Highlight the divide of country 
![2019-03-04_1749](https://user-images.githubusercontent.com/48204730/53741276-10926180-3ea7-11e9-855e-397591c6bb64.png)

**Comment by AnastasiyaSoroka** [comment]
Ask Olga

**Comment by wldyslw** [comment]
Done, will be published in the next build

**Comment by SKastsiukovich** [comment]
Done
