### ISSUE TITLE
Trivial: Choice of city: after reloading a page Minsk has been by default

### ISSUE THREAD

**Issue by Alena-Shurakova** [wldyslw/benefits.bugtracker#31]
**Describe the bug**
When user chooses any city (except Minsk) and then reloads a page, Minsk has become chosen city and all organization of Minsk presents on the map.

**To Reproduce**
1. Choose any city in the settings (except Minsk), for example, "Гродно".
2. Reload a page.
3. Open settings menu.

**Actual behavior**: the chosen city becomes "Минск"
**Expected behavior**: the chosen city stays "Гродно" as it was before reloading.

**Video:**
[reloading.zip](https://github.com/wldyslw/benefits.bugtracker/files/2926943/reloading.zip)

**Comment by wldyslw** [comment]
[Looks like] fixed in latest release

**Comment by Alena-Shurakova** [comment]
Fixed
