### ISSUE TITLE
Major: illogical sorting by name

### ISSUE THREAD

**Issue by Alena-Shurakova** [wldyslw/benefits.bugtracker#34]
**Describe the bug**
Bug is common both for web and mobile (Android, iOS) applications.

**To Reproduce**
1. After opening application, choose "Бары и пабы" category.
2. Sort it by name ("A-Я").

 
**Actual result**: 
Organizations are sorted illogically because:
1. if symbols ("«»", "# and so on)" in the name of organizations are ignored then it have to be sorted in the following way: 
«BierKeller»
«Clever Irish Pub»
Make-make Tiki King
etc.
2. if symbols in the name of organizations are not ignored then organizations have to sorted in the following way:
«BierKeller»
«Clever Irish Pub»
«На дне»
etc.

But none of this variants don't match the way how application realizes sorting by name.

**Screenshots**

Web client:
![image](https://user-images.githubusercontent.com/48205218/53792602-1e92c180-3f3d-11e9-8705-bd46f558821b.png)

Mobile:
[iOS.zip](https://github.com/wldyslw/benefits.bugtracker/files/2930182/iOS.zip)

**Comment by Alena-Shurakova** [comment]
The problem with recognition symbols ("«»", "# and so on)" is fixed **only on web version** (these symbols don't been taken into account during sorting), but there is another problem in the sorting by name: names which begin with numbers don't in order between each other.

**Steps** to reproduce:
1. Open all categories.
2. Sort it by name ("A-Я").

**Actual result**: at the beginning of the list is " 2English", "7 карат" and then "123".
**Expected result**: at the beginning of the list is "123" and then  " 2English","7 карат.

**Screenshot**: 
![image](https://user-images.githubusercontent.com/48205218/53943467-39487000-40ce-11e9-9fa3-fd5e7b0fc4da.png)

**Comment by wldyslw** [comment]
![image](https://user-images.githubusercontent.com/13451336/53945335-70b91b80-40d2-11e9-8114-a63fc662ae83.png)
Somehow my OS thinks that this kind of sorting is totally correct ¯\_(ツ)_/¯

**Comment by Alena-Shurakova** [comment]
The first problem with sorting is still reproduced on **the mobile app**.

**Comment by SKastsiukovich** [comment]
Fixed
