### ISSUE TITLE
Critical: Wrong Language in sorting

### ISSUE THREAD

**Issue by SKastsiukovich** [wldyslw/benefits.bugtracker#4]
Web
**STS**
Log in
In Language settings select English
Open Sorting
Observe
**Actual result:** Faced Belorussian Language 
**Expected result**: Only  English
![2019-03-04_1231](https://user-images.githubusercontent.com/48204730/53726249-a665c680-3e7e-11e9-8ed7-4cb80b7fd4b5.png)

**Comment by wldyslw** [comment]
Fixed in latest release

**Comment by SKastsiukovich** [comment]
Fixed
