### ISSUE TITLE
Major: No auto scrolling during sorting 

### ISSUE THREAD

**Issue by SKastsiukovich** [wldyslw/benefits.bugtracker#41]
**Steps to reproduce**
Start the app
Open any category or all categories
Swipe down to the center of list
Tap on any sorting
Observe

**Actual result:**
Focus stay on the center of list

**Expected result:**
The list should return to  the begin during the sorting

**Comment by wldyslw** [comment]
Fixed in the latest release

**Comment by SKastsiukovich** [comment]
Fixed on Web client.
Still reproduced on mobile.

**Comment by andrewworld** [comment]
Fixed in last release

**Comment by Alena-Shurakova** [comment]
Fixed on Android

**Comment by SKastsiukovich** [comment]
Fixed
