### ISSUE TITLE
Major: Incorrect behavior of adding pages with organization to favorites 

### ISSUE THREAD

**Issue by Alena-Shurakova** [wldyslw/benefits.bugtracker#43]
**Description of a bug:**
 After clicking element which are responsible for adding page to favorites on page of organization, nothing (what have to show user that element is added) happens, page doesn't been added to favorites. But after repeating navigation to the page which has been added, this page appears in favorites and responsible for adding element becomes red.

**Steps to reproduce:**
All steps are reproduced in the attached video file.
1. Launch mobile application.
2. Select any category.
3. Select any company.
4. Tap element which allows user to add page with organization to favorites, it current version of app (v 1.0.0) it is realized like:
![image](https://user-images.githubusercontent.com/48205218/53810648-7abf0b00-3f68-11e9-9d9d-078655246258.png)
5. Navigate to "Избранное" page
6. Navigate back to organization page which you are added to favorites
7. Navigate to "Избранное" page

**Actual result:**
 1. Page is added to favorites not after tapping responsible for it element, but after reviewing a page.
 2. After tapping element which are responsible for adding, nothing with element happens

**Expected result**: 
1. Page is added to favorites after tapping responsible for it element.
 2. After tapping element which are responsible for adding, this element becomes red (to show user that page is added to favorites).
 

**Video**

[mobile.zip](https://github.com/wldyslw/benefits.bugtracker/files/2931179/mobile.zip)

**Note:** Bug is common for Android and iOS OS.

**Comment by SKastsiukovich** [comment]
Reproduced on mobile

**Comment by andrewworld** [comment]
Fixed in last release

**Comment by Alena-Shurakova** [comment]
Fixed on Android

**Comment by SKastsiukovich** [comment]
Fixed
