### ISSUE TITLE
Critical: No Time out

### ISSUE THREAD

**Issue by SKastsiukovich** [wldyslw/benefits.bugtracker#44]
**Steps to reproduce**
Log in to web client
Don`t do anything 1h
Try do something
Observe
**Actual result**
Application working fine
**Expected result**
Redirection on log in page

**Comment by wldyslw** [comment]
I think this feature need to approved by Volha. Easy to implement, but still have doubts about it necessity

**Comment by SKastsiukovich** [comment]
Ok, I will discus

**Comment by wldyslw** [comment]
Added to the latest build with timeout of 2hrs

**Comment by LashaLoi** [comment]
Added to the latest build with timeout of 2hrs
