### ISSUE TITLE
Trivial: iDiscounts: Admin Web: Category name changed only after refreshing page

### ISSUE THREAD

**Issue by AnastasiyaSoroka** [wldyslw/benefits.bugtracker#46]
1. Open Admin Web
2. Log in
3. Select and edit any category
4. Change name
5. Click Изменить -> popup was closed

Actual result; Name wasn't changes. I opened Edit popup again -> there is new name
![17](https://user-images.githubusercontent.com/48205053/53878545-35104a00-401d-11e9-8de5-a7d7001b30be.png)
Expected result: Name was changed immediately.

**Comment by LashaLoi** [comment]
done

**Comment by AnastasiyaSoroka** [comment]
closed
