### ISSUE TITLE
Trivial: iDiscounts: Admin Web: Обновить button shouldn't return us to the Main page

### ISSUE THREAD

**Issue by AnastasiyaSoroka** [wldyslw/benefits.bugtracker#47]
1. Open Admin Web
2. Log in
3. Select any category
4. Select any Discount
5. Edit it
6. Click Обновить 

Actual result: page was closed, Not clear if changes were applied
Expected result: Data were updated. Discount page not closed. Button just means that changes were applied/saved

**Comment by LashaLoi** [comment]
done
