### ISSUE TITLE
Major: iDiscounts: Admin Web: Обновить дискаунт недоступна при заполненых обязательных полях

### ISSUE THREAD

**Issue by AnastasiyaSoroka** [wldyslw/benefits.bugtracker#48]
1. Open Admin Web
2. Log in
3. Select any category
4. Select any Discount and Edit it
Result: Обязательный поля заполнены но обновить не работает. 
![19](https://user-images.githubusercontent.com/48205053/53942903-fcc84480-40cc-11e9-9dd6-d9b94e0c3499.png)

**Comment by LashaLoi** [comment]
done
