### ISSUE TITLE
Major: iDiscounts: Admin Web: Создание/обновление бенефита: Добавление фотографии

### ISSUE THREAD

**Issue by AnastasiyaSoroka** [wldyslw/benefits.bugtracker#49]
1. Open Admin Web
2. Создание/редактировани бенефита
3. Выберете фотографию для бенефита

Actual result: не понятно, так выбрана фото или нет?
![22](https://user-images.githubusercontent.com/48205053/53943778-ef13be80-40ce-11e9-94f3-b4f8cc97c88f.png)

**Comment by AnastasiyaSoroka** [comment]
Тоже самое при редактировании бенефита с изображением. Не понятно есть ли картинка или нет

**Comment by LashaLoi** [comment]
done

**Comment by AnastasiyaSoroka** [comment]
и что изменилось?

![image](https://user-images.githubusercontent.com/48205053/53962471-35334700-40fc-11e9-878f-23aedf71fc77.png)

**Comment by LashaLoi** [comment]
done

**Comment by Alena-Shurakova** [comment]
Fixed.
