### ISSUE TITLE
Major: iDiscounts: Admin Web: Создание бенефита: Обязательные поля

### ISSUE THREAD

**Issue by AnastasiyaSoroka** [wldyslw/benefits.bugtracker#5]
1. Open Admin Web
2. Log in
3. Выберите город
4. Создание бенефита

Обязательные поля для заполнения никак не отмечены. Не ясно что заполнять.

**Comment by LashaLoi** [comment]
done

**Comment by AnastasiyaSoroka** [comment]
closed
