### ISSUE TITLE
Major: iDiscounts: Admin Web: create/update benefit: broken picture

### ISSUE THREAD

**Issue by AnastasiyaSoroka** [wldyslw/benefits.bugtracker#50]
1. Open Admin Web
2. Создание/редактировани бенефита
3. Выберете фотографию для бенефита
4. Сохраните бенефит

Actual result: картинка не видна
![24](https://user-images.githubusercontent.com/48205053/54115092-dd972300-43fc-11e9-8252-dd31f7c5c41a.png)

**Comment by LashaLoi** [comment]
done

**Comment by Alena-Shurakova** [comment]
Fixed.
