### ISSUE TITLE
Trivial: iDiscounts: Admin Web: Existing Benefit: Different style of + button

### ISSUE THREAD

**Issue by AnastasiyaSoroka** [wldyslw/benefits.bugtracker#51]
1. Open Admin Web
2. Log in
3. Select any category
4. Edit any benefit
5. Go to Скидки
6. Click + button -> it's grey
![image](https://user-images.githubusercontent.com/48205053/54115535-ad03b900-43fd-11e9-8ec3-3307774866fe.png)

Actual result
![image](https://user-images.githubusercontent.com/48205053/54115587-c73d9700-43fd-11e9-8a19-a130a1290628.png)

Expected result: In both cases I can see + button in one style

**Comment by LashaLoi** [comment]
done

**Comment by Alena-Shurakova** [comment]
Fixed.
