### ISSUE TITLE
Critical: when user's comment is fourth and more, and user delete it, he logs out.

### ISSUE THREAD

**Issue by Alena-Shurakova** [wldyslw/benefits.bugtracker#53]
**Describe the bug**:
When user's comment is fourth and more, and user delete it, he logs out.

**Steps to reproduce**:
1. Add to favorites the following organization which have different quantity of reviews (adding to favorites simplifies viewing of a bug):
 Squash-Life (has 1 review) 
«Diamond» (has 3 reviews)
#Тепло (has 4 reviews)
Гастро-паб (has 2 reviews)
2. Add to each organization your any rate and comment.
3. Delete added comments.

**Actual result**:
When user's comment is fourth and more, and user delete it, he logs out, comment is been deleted.

**Expected behavior**:
After deletion of comment user stays on the page where he has been before deletion,comment is been deleted.

**Video**:
[Discounts (1).zip](https://github.com/wldyslw/benefits.bugtracker/files/2952091/Discounts.1.zip)

**Comment by wldyslw** [comment]
Internal server problem, needs investigation

**Comment by LashaLoi** [comment]
done

**Comment by Alena-Shurakova** [comment]
Fixed.
