### ISSUE TITLE
Major: comment adds or deletes only after closing application

### ISSUE THREAD

**Issue by Alena-Shurakova** [wldyslw/benefits.bugtracker#54]
**Describe the bug**
When user adds or deletes comment, the result of adding/deletion shows to him only after closing and repeat launching application.

**Steps to reproduce**:
1. Launch application.
2. Open menu with all organizations and open any organization page.
3. Rate and comment it and go back to menu with all organizations.
4. Go back to the organization page, where you have left your rate and comment.
5. Relaunch application and  open the organization page, where you have left your rate and comment.
6. Try to delete your comment.
7. Relaunch application and  open the organization page, where you have left your rate and comment.

**Actual result**:
The result of adding/deletion shows to him only after closing and repeat launching application.

**Expected result**:
The result of adding/deletion shows immediately after performing these actions.

**Video**:
[2019_03_11_15_29_14.zip](https://github.com/wldyslw/benefits.bugtracker/files/2952179/2019_03_11_15_29_14.zip)

**Note**:
Reproduces on iOS, Android.

**Comment by andrewworld** [comment]
Fixed in last release

**Comment by Alena-Shurakova** [comment]
Fixed on Android
