### ISSUE TITLE
Major: incorrect way of filtering by categories

### ISSUE THREAD

**Issue by Alena-Shurakova** [wldyslw/benefits.bugtracker#55]
**Describe the bug:**
When user in one city selects category in the filter, then chooses another city (without removing selection), clicks on the any category (to see organizations only in this category) and than clicks this category again (to remove it), he can't see all organizations until he chooses all categories.

**Steps to reproduce:**
1. Open application and choose any city ( for example, "Минск")
2. In filters click on any one category (for example, "Бары и пабы")
3. Choose any other city (for example, "Гомель")
4. Click on any category in filters (for example, "Бары и пабы")
5. Click on it again .

**Actual result:**
After the second clicking on any category in filters in another city when none of categories are chosen, nothing shows on the map and in the list of organization and so as to see all available discounts user has to click on all categories.

**Expected result:**
When none of categories are chosen, user can see all organizations on the map and in the list.

**Video**:
[Discounts (2).zip](https://github.com/wldyslw/benefits.bugtracker/files/2960934/Discounts.2.zip)

**Comment by wldyslw** [comment]
Fixed, will be added in the next release

**Comment by SKastsiukovich** [comment]
Still reproduced

**Comment by wldyslw** [comment]
Tried to repeat by myself rn on staging, cannot reproduce. Could you please try again, maybe you've somehow checked it before I actually built latest release?

**Comment by SKastsiukovich** [comment]
Fixed
