### ISSUE TITLE
Trivial: iDiscounts: Admin Web: Edit benefit: incorrect name of field

### ISSUE THREAD

**Issue by Alena-Shurakova** [wldyslw/benefits.bugtracker#56]
**Steps to reproduce**:
1. Open application
2. Choose any benefit
3. Click on editing button

**Actual result**:
The name of field with discount is "Адрес*"

**Expected result**:
The name of field with discount is "Скидка*"

**Screenshots**
![image](https://user-images.githubusercontent.com/48205218/54282314-cac35080-45ac-11e9-836c-a1a96b001f7c.png)

**Comment by LashaLoi** [comment]
done

**Comment by Alena-Shurakova** [comment]
Fixed.
