### ISSUE TITLE
Major: iDiscounts: Web Admin:  Add benefit: it's possible to click "Добавить" button when some fields are empty

### ISSUE THREAD

**Issue by Alena-Shurakova** [wldyslw/benefits.bugtracker#57]
**Description of bug**:
"Добавить" button stays disabled till the time when user fills in all information.  When user deletes information from the fields "Широта","Долгота", "Скидка", "Адрес", the button isn't disabled.

**Steps to reproduce**:
1. Open application.
2. Click "Добавить бенефит" button
3. In opened window with adding benefit add all required information 
4. Delete information from the following fields: "Широта","Долгота", "Скидка", "Адрес"

**Actual result**:
After inputting all information and then deletion of listed above fields, "Добавить" button stays available for clicking.

**Expected result**:
When any of the obligatory for inputting fields are empty, Добавить" button should be disabled.

**Screenshot**:
![image](https://user-images.githubusercontent.com/48205218/54284597-4b844b80-45b1-11e9-9a90-4591d1eddfe8.png)

**Comment by LashaLoi** [comment]
done

**Comment by Alena-Shurakova** [comment]
Fixed.
