### ISSUE TITLE
Major: iDiscounts: Admin Web: Latitude and Longitude: incorrect behavior of app after inputting invalid data

### ISSUE THREAD

**Issue by Alena-Shurakova** [wldyslw/benefits.bugtracker#58]
**Steps to reproduce**:
1. Open application
2. Click on "Добавить бенефит" button
3.  Fill all the fields.
4. In the either "Широта" field or "Долгота"field before the meaning input any letter.
5. Click  "Добавить" button.

**Actual result**:
After inputting letters in this fields at the beginning of the field or letters than numbers, clicking "Добавить" button, it opens empty page and benefit hasn't been added, all inputted information is been lost.

**Expected result**:
After inputting invalid data and clicking  "Добавить" button, window with message that is inputted invalid data in the fields "Широта" и "Долгота" is opened

**Video:**
[Discounts admin.zip](https://github.com/wldyslw/benefits.bugtracker/files/2962046/Discounts.admin.zip)

**Comment by LashaLoi** [comment]
done

**Comment by Alena-Shurakova** [comment]
Fixed.
