### ISSUE TITLE
Major: iDiscounts: Web Admin: it's possible to add already existing category

### ISSUE THREAD

**Issue by Alena-Shurakova** [wldyslw/benefits.bugtracker#61]
**Steps to reproduce**:
1. Open application.
2. Choose any city (for example, "Гродно").
2. Open "Добавить категорию" button.
3. Add category which already exists (for example, "Доставка еды").

**Actual result**:
It is possible to add category which has already existed in the particular city.

**Expected result**:
It is impossible to add already existing category, it appears message that such a category has already been.

**Screenshots**
![image](https://user-images.githubusercontent.com/48205218/54342265-10375a80-464d-11e9-9193-45b296b0381e.png)

**Comment by LashaLoi** [comment]
done

**Comment by Alena-Shurakova** [comment]
Fixed
