### ISSUE TITLE
Major: iDiscounts: Web Admin: Edit benefit: Add location: expanded map doesn't function

### ISSUE THREAD

**Issue by Alena-Shurakova** [wldyslw/benefits.bugtracker#62]
**Description of the bug**:
When user add location in edit benefit form and uses expanded map, he can correctly to set a point of location on the map.

**Steps to reproduce**:
1. Open application.
2. Open any benefit.
3. Click on editing it.
4. Click on "Добавить локацию" button.
5. Open full size of map and try to add any location on the map.

**Actual result**:
Point on the map sets not in accordance with click.

**Expected result:**
Point on the map sets in accordance with click.

**Video**:
[Discounts admin.zip](https://github.com/wldyslw/benefits.bugtracker/files/2965827/Discounts.admin.zip)

**Comment by LashaLoi** [comment]
I deleted full size of map because I initially we didn't not think that the map would full size

**Comment by Alena-Shurakova** [comment]
Fixed.
