### ISSUE TITLE
Trivial: iDiscounts: Web Admin: incorrect way of reloading photo

### ISSUE THREAD

**Issue by Alena-Shurakova** [wldyslw/benefits.bugtracker#63]
**Steps to reproduce**:
1. Open application.
2. Click on "Добавить бенефит" button.
3. Input in all fields valid data and choose any photo in the button"Выберите фотографию".
4. After the photo is uploaded click on the button "Выберите фотографию".
5. Choose no another photo and cancel appeared window.

**Actual result**: photo which was uploaded earlier disappears after repeat opening window for choosing photo, although no photo was chosen.

**Expected result**: when user chooses one photo, than opens window for choosing another and doesn't choose any photo, the first photo stays.

**Video**:
[photo loading.zip](https://github.com/wldyslw/benefits.bugtracker/files/2965865/photo.loading.zip)

**Comment by LashaLoi** [comment]
done

**Comment by Alena-Shurakova** [comment]
Fixed
