### ISSUE TITLE
Blocker: Log in fails when it is inputted password

### ISSUE THREAD

**Issue by Alena-Shurakova** [wldyslw/benefits.bugtracker#66]
**Steps to reproduce**:
1. Log in admin version of Discount

**Actual result**:
There are no ability to log in

**Screenshot**:
![image](https://user-images.githubusercontent.com/48205218/55156149-3d662b80-516a-11e9-81ff-2d317304c94f.png)

**Comment by LashaLoi** [comment]
done

**Comment by Alena-Shurakova** [comment]
Fixed
