### ISSUE TITLE
Trivial: iDiscounts: Admin Web: Создание бенефита: Поля Широта и Долгота недоступны

### ISSUE THREAD

**Issue by AnastasiyaSoroka** [wldyslw/benefits.bugtracker#7]
1. Open Admin Web
2. Log in
3. Выберите город
4. Создание бенефита
5. Заполните поля Широта и Долгота

Результат: Поля Широта и Долгота недоступны для самостоятельного заполнения хотя выглядят как editable

**Comment by LashaLoi** [comment]
done
