### ISSUE TITLE
Major: iDiscounts: Admin Web: Создание бенефита: Нет возможности добавить дополнительный адрес без использования карты

### ISSUE THREAD

**Issue by AnastasiyaSoroka** [wldyslw/benefits.bugtracker#8]
1. Open Admin Web
2. Log in
3. Выберите город
4. Создание бенефита
5. Заполните поле с Адресом
6. Нажмите + чтобы ввести дополнительный адрес

Result: Появилась ошибка Укажите локацию на карте (широту, долготу)

![3](https://user-images.githubusercontent.com/48205053/53727132-88996100-3e80-11e9-84d0-1bd5a117b8f1.png)

Expected result: 
1. Широта и долгота заполнились сами в соответствии с указаным адресом
2. Поле ввода для второго адреса появилось

**Comment by AnastasiyaSoroka** [comment]
Актуально для окна Добавить локацию
![13](https://user-images.githubusercontent.com/48205053/53736234-349b7600-3e9a-11e9-83df-d8e39239be2c.png)

**Comment by LashaLoi** [comment]
done

**Comment by AnastasiyaSoroka** [comment]
Ничего не изменилось

![21](https://user-images.githubusercontent.com/48205053/53943562-672db480-40ce-11e9-995f-8fdbc9653009.png)

**Comment by LashaLoi** [comment]
У нас в приложении нельзя добавить просто локацию, к локациям обязательно должны быть привязаны координаты и не может быть локации без координат.

**Comment by Alena-Shurakova** [comment]
The problem is a similar to the problem in the following issue https://github.com/wldyslw/benefits.bugtracker/issues/9. Longitude an latitude should be automatically filled in accordance with inputted address.

**Comment by LashaLoi** [comment]
done ( добавлена кнопка "найти координаты по адресу")

**Comment by Alena-Shurakova** [comment]
When user inputs address and than click "Найди координаты по адресу" button, point on the map doesn't focus on this address, it stays where the last time it was added. This function is useful for checking if the right coordinates were found.

**Screenshot**:
![image](https://user-images.githubusercontent.com/48205218/54519961-a71b5400-4978-11e9-8fd4-48badea9a935.png)

**Comment by LashaLoi** [comment]
done

**Comment by Alena-Shurakova** [comment]
Fixed.
