### ISSUE TITLE
Critical: iDiscounts: Admin Web: Создание бенефита: Несоответствие адреса и широты/долготы

### ISSUE THREAD

**Issue by AnastasiyaSoroka** [wldyslw/benefits.bugtracker#9]
1. Open Admin Web
2. Log in
3. Выберите город
4. Создание бенефита
5. Заполните поле с Адресом
6. Выберите на карте любую точку

Result: Широта и Долгота заполнились со значением, которое несоответствует адресу

Expected result: Широта и Долгота заполнились со значением, которое соответствует адресу

**Comment by LashaLoi** [comment]
Я проверил, все нормально работает. Пожалуйста, попробуйте еще раз и попробуйте ввести те же координат на этом сайте https://www.mapcoordinates.net/ru

**Comment by Alena-Shurakova** [comment]
The problem is in the following: when user input address it is expected that latitude and longitude will be automatically inputted in the fields, but now user has to input address and then in addition to it to search for this address on the map so as to input latitude and longitude

**Comment by LashaLoi** [comment]
done ( добавлена кнопка найти координаты по адресу)

**Comment by SKastsiukovich** [comment]
Fixed
